version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: /usr/local/bundle
    ports:
      - '8888:8888'
    volumes:
      - .:/usr/src/app
      - gem_data:/usr/local/bundle
    command:
      bin/start_server.sh

volumes:
  gem_data:
